[features]
seeds = false
skip-lint = false

[programs.localnet]
solquad = "5dTxFCE8CjNc11j6tuQGqgMoh77oJRaC1TTZ89ihFySR"

[programs.devnet]
solquad = "5dTxFCE8CjNc11j6tuQGqgMoh77oJRaC1TTZ89ihFySR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[provider.devnet]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
